{{- if .Values.file.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{- include "uem.fileFullname" . }}
  labels:
    {{- include "uem.fileLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ae.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uem.fileSelectorLabels" . | nindent 4 }}
{{- end -}}