{{- if .Values.apple.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apple-hpa
  labels:
    {{- include "uem.appleLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apple
  minReplicas: {{ .Values.apple.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apple.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.apple.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apple.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apple.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apple.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
