{{- if .Values.bff.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uem.bffFullname" . }}
  labels:
    {{- include "uem.bffLabels" . | nindent 4 }}
spec:
  type: {{ .Values.apple.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uem.bffSelectorLabels" . | nindent 4 }}
{{- end -}}