{{- if and .Values.devices.enabled .Values.devices.metrics .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "uem.devicesFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.monitoring.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "uem.devicesFullname" . }}
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end -}}