{{- if .Values.ae.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "uem.aeFullname" . }}
  labels:
    {{- include "uem.aeLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ae.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uem.aeSelectorLabels" . | nindent 4 }}
{{- end -}}