{{- if .Values.windows.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{- include "uem.windowsFullname" . }}
  labels:
    {{- include "uem.windowsLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: windows
  minReplicas: {{ .Values.windows.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.windows.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.windows.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.windows.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.windows.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.windows.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
