{{- if .Values.windows.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{- include "uem.windowsFullname" . }}
  labels:
    {{- include "uem.windowsLabels" . | nindent 4 }}
spec:
  type: {{ .Values.windows.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uem.windowsSelectorLabels" . | nindent 4 }}
{{- end -}}